# Generated by Django 5.0.4 on 2024-05-13 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesAndQuizes', '0003_userlesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursesAndQuizes.lesson')),
            ],
        ),
    ]
